# Configuration of Hugo
title: 池川航史
baseURL: 'https://ikegawa-koshi.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: ja
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$, ^_sample]
permalinks:
  authors: '/author/:slug/'
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
markup:
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
